version: '2.1'
services:
  keycloak:
    container_name: keycloak
    # image: quay.io/keycloak/keycloak:22.0.3
    image: quay.io/keycloak/keycloak:23.0.7
    # image: quay.io/keycloak/keycloak:24.0.2
    environment:
      # Enable health and metrics support
      - KC_HTTP_PORT=8080
      - KC_HEALTH_ENABLED=true
      - KC_METRICS_ENABLED=true
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KC_HTTP_RELATIVE_PATH=/auth
      - KC_HOSTNAME_STRICT=false
      - KC_HTTP_ENABLED=true
    volumes:
      - ./export:/opt/keycloak/data/import:Z
    command:
      - start
      - --import-realm
    ports:
      - "8080:8080"
